// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyNhanVien.Models;

namespace QuanLyNhanVien.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("QuanLyNhanVien.Models.NhanVien", b =>
                {
                    b.Property<int>("intMaNhanVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<bool>("boolGioiTinh")
                        .HasColumnType("bit");

                    b.Property<double>("dblLuong")
                        .HasColumnType("float");

                    b.Property<int>("intMaPhongBan")
                        .HasColumnType("int");

                    b.Property<int>("intNamSinh")
                        .HasColumnType("int");

                    b.Property<int>("intTrangThai")
                        .HasColumnType("int");

                    b.Property<string>("strTenNhanVien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("intMaNhanVien");

                    b.HasIndex("intMaPhongBan");

                    b.ToTable("NhanVien");

                    b.HasData(
                        new
                        {
                            intMaNhanVien = 1,
                            boolGioiTinh = true,
                            dblLuong = 15000000.0,
                            intMaPhongBan = 1,
                            intNamSinh = 1995,
                            intTrangThai = 0,
                            strTenNhanVien = "Nguyen Van A"
                        },
                        new
                        {
                            intMaNhanVien = 2,
                            boolGioiTinh = false,
                            dblLuong = 12000000.0,
                            intMaPhongBan = 2,
                            intNamSinh = 1998,
                            intTrangThai = 1,
                            strTenNhanVien = "Tran Thi B"
                        },
                        new
                        {
                            intMaNhanVien = 3,
                            boolGioiTinh = true,
                            dblLuong = 20000000.0,
                            intMaPhongBan = 3,
                            intNamSinh = 1990,
                            intTrangThai = 0,
                            strTenNhanVien = "Le Van C"
                        },
                        new
                        {
                            intMaNhanVien = 4,
                            boolGioiTinh = false,
                            dblLuong = 10000000.0,
                            intMaPhongBan = 4,
                            intNamSinh = 2000,
                            intTrangThai = 2,
                            strTenNhanVien = "Pham Thi D"
                        },
                        new
                        {
                            intMaNhanVien = 5,
                            boolGioiTinh = true,
                            dblLuong = 18000000.0,
                            intMaPhongBan = 1,
                            intNamSinh = 1995,
                            intTrangThai = 0,
                            strTenNhanVien = "Hoang Van E"
                        },
                        new
                        {
                            intMaNhanVien = 6,
                            boolGioiTinh = false,
                            dblLuong = 14000000.0,
                            intMaPhongBan = 2,
                            intNamSinh = 1997,
                            intTrangThai = 0,
                            strTenNhanVien = "Ngo Thi F"
                        });
                });

            modelBuilder.Entity("QuanLyNhanVien.Models.PhongBan", b =>
                {
                    b.Property<int>("intMaPhongBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("strTenPhongBan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("intMaPhongBan");

                    b.ToTable("PhongBan");

                    b.HasData(
                        new
                        {
                            intMaPhongBan = 1,
                            strTenPhongBan = "Phong Ky Thuat"
                        },
                        new
                        {
                            intMaPhongBan = 2,
                            strTenPhongBan = "Phong Nhan Su"
                        },
                        new
                        {
                            intMaPhongBan = 3,
                            strTenPhongBan = "Phong Ke Toan"
                        },
                        new
                        {
                            intMaPhongBan = 4,
                            strTenPhongBan = "Phong Kinh Doanh"
                        });
                });

            modelBuilder.Entity("QuanLyNhanVien.Models.NhanVien", b =>
                {
                    b.HasOne("QuanLyNhanVien.Models.PhongBan", "objPhongBan")
                        .WithMany("lstNhanVien")
                        .HasForeignKey("intMaPhongBan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("objPhongBan");
                });

            modelBuilder.Entity("QuanLyNhanVien.Models.PhongBan", b =>
                {
                    b.Navigation("lstNhanVien");
                });
#pragma warning restore 612, 618
        }
    }
}
